name: Navi
description: LX Exhibition companion app.

version: 1.1.4+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^1.6.7
  cupertino_icons: ^0.1.2
  cloud_firestore: ^0.13.5
  google_maps_flutter: ^0.5.25+2
  firebase_messaging: ^6.0.12
  share: ^0.6.4
  localstorage: ^3.0.2+5
  url_launcher: ^5.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - images/activity/